FROM node:20

# Set working directory
WORKDIR /usr/src/app

# Copy the rest of the application code
COPY . .

# Install dependencies
RUN npm install

# Expose the port the app runs on
#EXPOSE 3000

# Start the app
#CMD ["npm", "start"]